### ISSUE TITLE
Release new version compatible with Rails 8.0

### ISSUE THREAD

**Issue by ohbarye** [abicky/activerecord-debug_errors#11]
Hi @abicky !

Would you mind if I ask for a new version to be published, including https://github.com/abicky/activerecord-debug_errors/pull/10 ? I'm planning to update my team's Rails app to 8.0.

**Comment by abicky** [comment]
I've just released [v0.1.4](https://rubygems.org/gems/activerecord-debug_errors/versions/0.1.4).
I thought I didn't need to release a new version because I hadn't modified the main code but I realized that the previous version had the condition `spec.add_runtime_dependency "activerecord", ">= 6", "< 8"` (https://github.com/abicky/activerecord-debug_errors/commit/a0e840fd6e1d39a6c5ea8c64dda97242f7fc0317)...

**Comment by ohbarye** [comment]
@abicky, I really appreciate your quick action!
